### ISSUE TITLE
[Tracking Issue] Code Refactor

### ISSUE THREAD

**Issue by Flouse** [ckb-cell/rgbpp-sdk#37]
- [x] Is this line unused?
   _Originally posted by @Flouse in https://github.com/ckb-cell/rgbpp-sdk/pull/26#discussion_r1533324544_
   fixed in https://github.com/ckb-cell/rgbpp-sdk/pull/38

- [x] Review the logic of BTC transaction fee calculation
  https://learnmeabitcoin.com/technical/transaction/size/#weight

- [x] https://github.com/ckb-cell/rgbpp-sdk/issues/82

- [x] replace all `void 0` to `undefined`
  _Originally posted by @ShookLyngs in https://github.com/ckb-cell/rgbpp-sdk/pull/149#discussion_r1584164462_

**Comment by ShookLyngs** [comment]
Enabling the RBF feature (allowing transactions to be replaced) is easy, but how to sign and send the same transaction again is a problem. The issue is that when we got the UTXOs to construct a transaction, we got them from the btc-assets-api. And once the transaction is constructed, it no longer contains some required properties for us to "reverse" the whole construction process and convert a Transaction to a PSBT.

For example, how does the process know which output (vout) in the transaction can be altered in order to pay more fees? And besides, what's the dust limit for each output? Since outputs can be normal UTXOs (dust_limit=1,0000) or RGBPP UTXOs (dust_limit=546)._limit=546).
